development:
  admin_name: admin
  admin_email: zk.amazing@gmail.com
  admin_password: 12345678
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  domain_name: example.com
  secret_key_base: aedfb72f8399c4e2ffff24450fbe8970a5b495a63931cb35e8ee1902da178f8f0dc182af3e0755087be8b920d4080ed7cb015084d7d9ab80434b9acc44acffc1


test:
  domain_name: example.com
  secret_key_base: aedfb72f8399c4e2ffff24450fbe8970a5b495a63931cb35e8ee1902da178f8f0dc182af3e0755087be8b920d4080ed7cb015084d7d9ab80434b9acc44acffc1


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
